/*

CREATE DATABASE CTO_UAT_AAD_SS_20150625 ON 
( NAME = N'ITPolicy_Central_Ref', 
FILENAME = N'D:\CTO_UAT_AAD_SS_20150625.ss' ) 
AS SNAPSHOT OF CTO_UAT_AAD;

ALTER DATABASE CTO_UAT_AAD
SET RESTRICTED_USER
WITH ROLLBACK IMMEDIATE;
GO

RESTORE DATABASE CTO_UAT_AAD 
from DATABASE_SNAPSHOT = 'CTO_UAT_AAD_SS_20150625'
GO

ALTER DATABASE CTO_UAT_AAD
SET MULTI_USER
WITH ROLLBACK IMMEDIATE;
GO

DROP DATABASE CTO_UAT_AAD_SS_20150625;

*/

--CREATE DATABASE CTO_PRD_AAD_SS_20150625 ON 
--( NAME = N'ITPolicy_Central_Ref', 
--FILENAME = N'D:\CTO_PRD_AAD_SS_20150625.ss' ) 
--AS SNAPSHOT OF CTO_PRD_AAD;

ALTER DATABASE CTO_PRD_AAD
SET RESTRICTED_USER
WITH ROLLBACK IMMEDIATE;
GO

RESTORE DATABASE CTO_PRD_AAD 
from DATABASE_SNAPSHOT = 'CTO_PRD_AAD_SS_20150625'
GO

ALTER DATABASE CTO_PRD_AAD
SET MULTI_USER
WITH ROLLBACK IMMEDIATE;
GO

update CTO_PRD_AAD..HAB_USER set
	END_DT = '20990101',
	LAST_LOGIN_DATE = GETDATE()
where  USER_ID = 1
Go

--DROP DATABASE CTO_PRD_AAD_SS_20150625;
